### ISSUE TITLE
官方好像升级了，传入PlayAuth已经下载出来的文件不能播放

### ISSUE THREAD

**Issue by allanwong** [lbbniu/aliyun-m3u8-downloader#10]
playInfo := sj.Get("PlayInfoList").Get("PlayInfo").GetIndex(len(playInfoList) - 1)
==>
playInfo := sj.Get("PlayInfoList").Get("PlayInfo").GetIndex(len(playInfoList) - 2)

**Comment by lbbniu** [comment]
这是选择视频清晰度的不同链接
