### ISSUE TITLE
2023/03/31 05:48:10 type assertion to []interface{} failed

### ISSUE THREAD

**Issue by bibinocode** [lbbniu/aliyun-m3u8-downloader#21]
![image](https://user-images.githubusercontent.com/69722766/228972016-38194611-3a30-4623-bbe6-a68cbc5325fa.png)
请问这是什么原因导致

**Comment by lbbniu** [comment]
方便加个微信吗？发个PlayAuth 和 视频id 我这边调试下吗？ 微信：lbbniu-com
