### ISSUE TITLE
aliyun方式返回get PlayInfo err

### ISSUE THREAD

**Issue by kyay006** [lbbniu/aliyun-m3u8-downloader#25]
请问aliyun的VOD加密方式是否还能下载到？
我按照使用说明执行
aliyun-m3u8-downloader aliyun -p "PlayAuth" -v 视频id -o=/data/example --chanSize 1
返回
2023/05/04 00:00:44 donwload: get PlayInfo err: type assertion to []interface{} failed

不知道是否因为我的playauth和视频id有误?
![image](https://user-images.githubusercontent.com/25722732/235976353-ef7c5910-1b53-4b2c-993b-e4b357677b35.png)

**Comment by lbbniu** [comment]
视频id应该是 vodVideoId 字段

**Comment by lbbniu** [comment]
欢迎加微信私聊
