### ISSUE TITLE
私有加密的webplayauth是什么？

### ISSUE THREAD

**Issue by Ausli** [lbbniu/aliyun-m3u8-downloader#3]
能不能说明一下WebPlayAuth是怎么来的，是直接用m3u8的地址还是什么

**Comment by flxxyz** [comment]
看文档
[https://help.aliyun.com/document_detail/52833.html](https://help.aliyun.com/document_detail/52833.html)

![image](https://user-images.githubusercontent.com/8678079/165213206-461f0652-ee09-4c9b-a44c-a691ae9bd9dc.png)
