### ISSUE TITLE
请问阿里云的PlayAuth是什么格式的？

### ISSUE THREAD

**Issue by ccquan** [lbbniu/aliyun-m3u8-downloader#30]

**Comment by gbabybus** [comment]
阿里云的playauth是一个base64字符串，解析之后是一个json字符串，例如我下面给出的这个


.\aliyun-m3u8-downloader.exe aliyun -p "eyJTZWN1cml0eVRva2VuIjoiQ0FJU2lBTjFxNkZ0NUIyeWZTaklyNUROSTlYbmc3ZFRncnJjUkdmTGlXY3hQZmxZdHBEWWtEejJJSDFQZlhGdEFlMFp0LzArbVdsUTV2d2FscklxRXNRZkd4ZWRNWkVwdHNrSXJseitKb0hidk5ldTBic0hoWnY5K2VObTBmU2lqcUhvZU96Y1lJNzMwWjdQQWdtMlEwWVJySkwrY1RLOUphYk1VL21nZ29KbWFkSTZSeFN4YVNFOGF2NWRPZ3BscnIwSVZ4elBNdnIvSFJQMnVtN1pIV3R1dEEwZTgzMTQ1ZmFRejlHaTZ4YlRpM2I5ek9FVXFPYVhKNFMvUGZGb05ZWnlTZjZvd093VUVxL2R5M3hvN3hGYjFhRjRpODRpL0N2YzdQMlFDRU5BK3dtbFB2dTJpOE5vSUYxV2E3UVdJWXRncmZQeGsrWjEySmJOa0lpbDVCdFJFZHR3ZUNuRldLR216c3krYjRIUEROc2ljcXZoTUhuZ3k4MkdNb0tQMHprcGVuVUdMZ2hIQ2JGRFF6MVNjVVYxRVd1RWNmYjdvZ21TUDFqOEZQZS92ZnRvZ2NZdi9UTEI1c0dYSWxXRGViS2QzQnNETjRVMEIwRlNiRU5OaERTOEt2SlpLbFVkTGdvL1Yrek5WL2xhYUJGUHRLWFdtaUgrV3lOcDAzVkxoZnI2YXVOcGJnUHIxVVFwTlJxQUFRdTkxbUZ1ektCM1IwT2lvN2NDYWYzeUVXSitGK1o2VnBDWnpKbm1DeDVNanZzbHFsckt3c1B2ejRGMHE1NjB6dmZ2TFNDUkF4TXh4UTdoNFJZVEhXaG5rOVE0ekhkMmZ1NDlFbHpId2VjdHdjNVZIcmk0SjdPS1dlNnBTS2x3VDREb0hBdmNjRFozU08yaUk3cDlHTlZkcEVmbDJlT3V1NmZtaDhqSUYwVU8iLCJBdXRoSW5mbyI6IntcIkNJXCI6XCJRclhQMU1PVnYvUU1TWGkxWEExazRoa0tERVowWTZoSXhmYzBUMGpjVndHQm4wTS9NTkkzY3RKcFJnUEdmV2lyblE2VmFranRBSFRtZjN6VWV2NFFld29PYlFxSnFwR0JzYU8rV2FJL01TVT1cIixcIkNhbGxlclwiOlwiWUNYeGJ5MUw0TGJDMkpVQW91OW5tdmFKbUtlQ0dQM01zc1J2MlFHZTNRdz1cIixcIkV4cGlyZVRpbWVcIjpcIjIwMjMtMDUtMTZUMTk6Mjk6NTJaXCIsXCJNZWRpYUlkXCI6XCI2MDkzZDZkMGM5MzM3MWVkYmY4MzA2NzVhMGVjMDEwMlwiLFwiUGxheURvbWFpblwiOlwidjMwLjUxY3RvLmNvbVwiLFwiU2lnbmF0dXJlXCI6XCJJQlZ4ejlnai9RQWs0N2RmVFl2R1E5L3BRVGM9XCJ9IiwiVmlkZW9NZXRhIjp7IlN0YXR1cyI6Ik5vcm1hbCIsIlZpZGVvSWQiOiI2MDkzZDZkMGM5MzM3MWVkYmY4MzA2NzVhMGVjMDEwMiIsIlRpdGxlIjoiMS5kb2NrZXLlronoo4Xpg6jnvbIiLCJDb3ZlclVSTCI6Imh0dHBzOi8vdjMwLjUxY3RvLmNvbS82MDkzZDZkMGM5MzM3MWVkYmY4MzA2NzVhMGVjMDEwMi9zbmFwc2hvdHMvNWE0YTliZTI1NjdlNDQ2ZjhkMTQwMzU0ZTQyZTIzMzItMDAwMDMuanBnIiwiRHVyYXRpb24iOjM2OS4yN30sIkFjY2Vzc0tleUlkIjoiU1RTLk5TeGhvU25ocjV4N0ZBem1nZDF2dFlVc3IiLCJQbGF5RG9tYWluIjoidjMwLjUxY3RvLmNvbSIsIkFjY2Vzc0tleVNlY3JldCI6IkNvUjZ6aXIxOWN1OGpBUnI3S2Q2ZnVNQ0p4Y0tlbUpib0szTWthdG1XNXNTIiwiUmVnaW9uIjoiY24tc2hhbmdoYWkiLCJDdXN0b21lcklkIjoxMTMyNjMxNDIxMDU3Nzc3fQ==" -v "6093d6d0c93371edbf830675a0ec0102" -o ./

**Comment by lbbniu** [comment]
playauth 只能使用一次
