### ISSUE TITLE
InvalidAuthInfo.ExpireTime

### ISSUE THREAD

**Issue by windcludy** [lbbniu/aliyun-m3u8-downloader#31]
执行下面的命令的时候报错了【InvalidAuthInfo.ExpireTime】
这个Token有效期间是（\"ExpireTime\":\"2023-05-23T09:10:10Z\"）

aliyun-m3u8-downloader.exe  aliyun -p "eyJTZWN1cml0eVRva2VuIjoiQ0FJU2lBTjFxNkZ0NUIyeWZTaklyNWJ0QTh2K29iaGs5WU96YUdEV2d6VWhZczFhaC9UTmxEejJJSGxPZTNKckF1a1dzdnd3bW10UzdmNFpscklxRU04WkdoeVZOWmNvdDg4UHFWbjZKb0hidk5ldTBic0hoWnY5cDZZZ28vS2lqcUhvZU96Y1lJNzMwWjdQQWdtMlEwWVJySkwrY1RLOUphYk1VL21nZ29KbWFkSTZSeFN4YVNFOGF2NWRPZ3BscnIwSVZ4elBNdnIvSFJQMnVtN1pIV3R1dEEwZTgzMTQ1ZmFRejlHaTZ4YlRpM2I5ek9FVXFPYVhKNFMvUGZGb05ZWnlTZjZvd093VUVxL2R5M3hvN3hGYjFhRjRpODRpL0N2YzdQMlFDRU5BK3dtbFB2dTJpOE5vSUYxV2E3UVdJWXRncmZQeGsrWjEySmJOa0lpbDVCdFJFZHR3ZUNuRldLR216c3krYjRIUEROc2ljcXZoTUhuZ3k4MkdNb0tQMHprcGVuVUdMZ2hIQ2JGRFF6MVNjVVYzR20yRmV2Ny9wQWlUT1YvN0VmTy92ZnRvZ2NZdi9UTEI1c0dYSWxXRGViS2QzQnNETjRVMEIwRlNiRWRNZ2plNktmWldMMVFUTFFnOVhPN09WL2xhYUJGUHRLWFdtaUgrV3lOcDAzVkxoZnI2YXVOcGJnUHIxVVFwTlJxQUFXa29XTGJMOXpqY1g5eGNTMmhWTDNWYU9jRGtqMWJvNkRCeEw1WThFeFRjU2U1TlQ4bW01OU1uTDdVRi9rV2J5MTgvNHRNZXVidnFSbjh1Uzh3V3RFWTd0TkVGU3NoSTR3VmowQXF2ckEvRUtsZjBxSTlIQytwQmpQYi8rNWo3dHI1WlZsdTQrVkNEVkZHb1V4MWFzQ1NPcVF2NnpUZVNZUzRuNGpSNmFmSkIiLCJBdXRoSW5mbyI6IntcIkNJXCI6XCIraVJNMVF1MFdsVTJLb1ZnUEhibzNvb3VldFozbWoxQmlFelVYdWpQQTc0Slppbm9PUFUrRWE0QzBTNGFpdHcrN3F5eFFNdndPN2ZGQUYvdWhKaWtWbWhiazl0OThid0hLeVJKQkdwbEtoYz1cIixcIkNhbGxlclwiOlwiVUZyVm9wMU1QOHMvNzliSHNQRTFEOXRXSEpCUFpQSWhpY3c5UHYvUzlQZz1cIixcIkV4cGlyZVRpbWVcIjpcIjIwMjMtMDUtMjNUMDk6MTA6MTBaXCIsXCJNZWRpYUlkXCI6XCJjNDFiYzdmOWQwZDM0ZjhjYjljYTA5NTQwODIyMmM4M1wiLFwiUGxheURvbWFpblwiOlwidmlkZW8ucWtkdW8uY25cIixcIlNpZ25hdHVyZVwiOlwiWk5ueVlXUjJDNUVCbTlINmJqSmJRY3BNQldRPVwifSIsIlZpZGVvTWV0YSI6eyJTdGF0dXMiOiJOb3JtYWwiLCJWaWRlb0lkIjoiYzQxYmM3ZjlkMGQzNGY4Y2I5Y2EwOTU0MDgyMjJjODMiLCJUaXRsZSI6IuaWsOeJiC3otoXog73oi7Hor63ljZXor43or74yIiwiQ292ZXJVUkwiOiJodHRwczovL3ZpZGVvLnFrZHVvLmNuL2M0MWJjN2Y5ZDBkMzRmOGNiOWNhMDk1NDA4MjIyYzgzL3NuYXBzaG90cy9mMzA5ODA3YTc4MjE0YzI0YWQ1MmM4Yjc0YWIyYmFkNy0wMDAwNS5qcGciLCJEdXJhdGlvbiI6MzY1OS44ODI2fSwiQWNjZXNzS2V5SWQiOiJTVFMuTlVYSHFKTGdFQkFYakZnZzV0bkJ2aDFmdiIsIlBsYXlEb21haW4iOiJ2aWRlby5xa2R1by5jbiIsIkFjY2Vzc0tleVNlY3JldCI6IjNnckNHQmlOd0I5aGJQZVJQOUFwUjdCRXl0UzdYaWt3WE43NUU0QThqa3I0IiwiUmVnaW9uIjoiY24tc2hhbmdoYWkiLCJDdXN0b21lcklkIjoxMzg0Nzg5MDQwMTMwMDIzfQ==" -v "c41bc7f9d0d34f8cb9ca095408222c83" -o=./ --chanSize 1

2023/05/23 18:23:05 {"Code":"InvalidAuthInfo.ExpireTime","HostId":"vod.cn-shanghai.aliyuncs.com","Message":"The specified parameter AuthInfo has expired.","Recommend":"https://next.api.aliyun.com/troubleshoot?q=InvalidAuthInfo.ExpireTime\u0026product=vod","RequestId":"91E42F25-95B9-550D-879A-FE8483122E5A"}
2023/05/23 18:23:05 donwload: get PlayInfo err: type assertion to []interface{} failed

**Comment by lbbniu** [comment]
playauth过期，请重新获取
