### ISSUE TITLE
使用方面的疑问

### ISSUE THREAD

**Issue by Mnzm-zh** [lbbniu/aliyun-m3u8-downloader#6]
请问作者，./aliyun-m3u8-downloader aliyun -p "WebPlayAuth" -v 视频id -o=/data/example --chanSize 1
其中的WebPlayAuth 和  视频id 分别是什么？
我所拥有的只有一个url,如何从中提取这两个参数呢？
例如：https://video.hjstu.com/2b7fc12621174620a5e6c9031789fc9a/559dc7b786b0e04a396c894248a3d3se-hd-encryut-stream.m3u8?auth_key=1655805277-null-null-1e67bd00a5ee876dceb2f96cndcab839

**Comment by flxxyz** [comment]
没有相关知识，不建议用，或者你多看看文档

**Comment by lbbniu** [comment]
分析业务服务接口，肯定有获取视频id和WebPlayAuth的接口
