### ISSUE TITLE
你好，可以告知如何在下载时就定义文件名吗

### ISSUE THREAD

**Issue by Sukidao** [lbbniu/aliyun-m3u8-downloader#8]
你好，可以告知如何在下载时就定义文件名吗

**Comment by lbbniu** [comment]
aliyun 下载自动获取的文件名

**Comment by lbbniu** [comment]
其他m3u8 格式是后去的url中的路径作为文件名

**Comment by lbbniu** [comment]
欢迎提交pr支持指定保存文件名

**Comment by Sukidao** [comment]
感谢回复，没有学习过go语言。最近在学习python，偶然间发现这个小工具，赞！

**Comment by lbbniu** [comment]
> 感谢回复，没有学习过go语言。最近在学习python，偶然间发现这个小工具，赞！

我抽时间支持下自定义保存文件名
