### ISSUE TITLE
友情提示，下载阿里云私有加密m3u8返回的音频文件

### ISSUE THREAD

**Issue by Sukidao** [lbbniu/aliyun-m3u8-downloader#9]
pkg/parse/aliyun/aliyun_url.go中
StreamType=video
修改为
StreamType=audio即可

**Comment by lbbniu** [comment]
> pkg/parse/aliyun/aliyun_url.go中 StreamType=video 修改为 StreamType=audio即可

可以提交pr支持音频文件下载吗
